version: '3'

services:
  server:
    image: dictionary-app-server
    build:
      context: ./server
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_URL=mongodb://root:example@mongo:27018/dictionaryApp?authSource=admin
      - MONGO_SERVICE=mongo
    # limit logs
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    

  mongo:
    ports:
      - 27018:27018
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      # Set mondo db storage voulume name.
      - mongo-db:/data/db
    # limit logs
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  
  client:
    image: dictionary-app-client
    build: 
      context: ./client
    restart: always
    # limit logs
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo-db: